IgnorePath "/.*"
IgnorePath "/*.cache"
IgnorePath "/boot/*"
IgnorePath "*.snapshots*"

IgnorePath "/etc/*shadow*"
IgnorePath "/etc/.*"
IgnorePath "/etc/NetworkManager/*"
IgnorePath "/etc/audit/*"
IgnorePath "/etc/ca-certificates/*"
IgnorePath "/etc/crypttab"
IgnorePath "/etc/dconf.d"
IgnorePath "/etc/default/*"
IgnorePath "/etc/fonts/*"
IgnorePath "/etc/fstab"
IgnorePath "/etc/group*"
IgnorePath "/etc/machine-id"
IgnorePath "/etc/mkinitcpio.conf"
IgnorePath "/etc/os-release"
IgnorePath "/etc/pacman.d/*"
IgnorePath "/etc/passwd*"
IgnorePath "/etc/resolv.conf"
IgnorePath "/etc/shells"
IgnorePath "/etc/ssl/*"
IgnorePath "/etc/sub*id*"
IgnorePath "/etc/ufw/*"
IgnorePath "/etc/userdb"

IgnorePath "/opt/*"

IgnorePath "/swp/swapfile"

IgnorePath "/usr/lib/*"
IgnorePath "/usr/share/*"

IgnorePath "/var/*"
