set -Ux XDG_CACHE_HOME "$HOME/.cache"
set -Ux XDG_CONFIG_HOME "$HOME/.config"
set -Ux XDG_DATA_HOME "$HOME/.local/share"
set -Ux XDG_STATE_HOME "$HOME/.local/state"

set -Ux GNUPGHOME "$XDG_DATA_HOME/gnupg"
set -Ux GTK2_RC_FILES "$XDG_CONFIG_HOME/gtk-2.0/gtkrc":"$XDG_CONFIG_HOME/gtk-2.0/gtkrc.mine"
set -Ux HISTFILE "$XDG_STATE_HOME/bash/history"
set -Ux JAVA_OPTIONS "-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
set -Ux MAVEN_ARGS "--settings $XDG_CONFIG_HOME/maven/settings.xml"
set -Ux MAVEN_OPTS "-Dmaven.repo.local=$XDG_DATA_HOME/maven/repository"
set -Ux PYTHONPYCACHEPREFIX "$XDG_CACHE_HOME/python"
set -Ux PYTHONUSERBASE "$XDG_DATA_HOME/python"
set -Ux PYTHON_HISTORY "$XDG_STATE_HOME/python_history"
set -Ux SQLITE_HISTORY "$XDG_STATE_HOME/sqlite_history"
set -Ux WGETRC "$XDG_CONFIG_HOME/wgetrc"
